<?php
/**
 * Created by PhpStorm.
 * User: Serhii
 * Date: 27.03.2018
 * Time: 20:44
 */
return [
    //finance - класс финансов
    "The market is having a hard time adjusting to a new day. A few points of market stood out from his first official meeting as head of the central bank: He is likely to focus more on data than theory; he's not going to be a slave to projections; and he's less, well, verbose than the market's come to expect, at least in recent history.",
    "Fed Chair Powell warns some asset prices are 'elevated' including stocks. Powell said he doesn't see any significant risks in the current financial system. He cited how the banking sector has higher liquidity, less leverage, and lower risk taking compared to the financial crisis.",
    "Powell says Trump's trade policy has become a growing concern among Federal Reserve members. In his first news conference as central bank chairman, Jerome Powell said the battle over tariffs has not caused Fed officials to change their economic outlook yet, but future expectations will depend on how the situation unfolds. However, a number of participants reported that about their conversations with business leaders around the country and reported that trade policy has come a concern going forward for that growth.",
    "Fed still expects 3 rate hikes this year, but will pick up the pace in 2019 The Federal Reserve said Wednesday that it sees the federal funds rate at 2.1 percent by the end of 2018, unchanged from its December forecast. But the central bank raised its 2019 projection, saying it sees the benchmark rate at 2.9 percent. That's up from the 2.7 percent estimate it published in December. The Fed also upped its 2020 forecast to 3.4 percent from 3.1 percent.",
    "Fed hikes rates and raises GDP forecast again. Along with the increase came another upgrade in the Fed's economic forecast, and a hint that the path of rate hikes could be more aggressive. The market currently expects three hikes for 2018, and that remained the baseline forecast, but at least one more increase was added in the following two years.",
    //power engineering - класс энергетики
    "Arkansas Electric Cooperative Corporation has entered into a power purchase agreement with Renewable Energy Systems Americas Inc. to purchase up to 100 MW of energy that will be produced by an 800-acre solar farm near Crossett in 2021.",
    "The addition of the 100 megawatts of solar capacity produced by the Crossett Solar Energy Farm will provide AECC with additional reasonably priced power that is ultimately delivered to the more than 1.2 million electric cooperative members in Arkansas, said Duane Highley, president and CEO of AECC. AECC's generation fuel portfolio now includes more than 17 percent of hydropower, solar, wind and biomass generation which supplements our traditional generation facilities.",
    "In addition to the world record, the 120-MW battery will benefit Gupta by supporting a new solar facility being built at Whyalla steelworks plant.",
    "A legal battle over the storage of more than 3 million tons of coalash in Virginia is headed to a federal appeals court in a case closely watched by environmentalists and energy companies. The case pits the Sierra Club against the state's largest electric utility, Dominion Energy",
    "An Arc flash at an electrical bus near the cooling towers of the Tennessee Valley Authority’s Sequoyah nuclear Nuclear Power Plant put two contract workers in the hospital,the Chattanooga Times Free Press reported.",
    //property - класс недвижимости
    "Property price growth in Edinburgh outperforms all other UK cities. Average prices in the city reached a record high of £285,000 and the total value of Edinburgh’s housing stock grew by £7.5 billion from £61.4 billion in 2016 to £68.9 billion last year, more than any other local authority district in the UK as a whole. Overall Scotland has seen its strongest housing market since 2007, with price growth now outperforming London and values are expected to continue to rise due to a lack of supply, according to the latest research report from Savills",
    "Market report: house prices in London up £4,000 in a month but annual prices skip traditional spring surge.New seller numbers were three per cent lower this month than they were a year ago, at a time of year when homeowners usually rush to put their properties  property up for sale.This is good news for buyers, because it  strengthens their bargaining power, said Shipside, but they will also have a smaller range of property to choose from as homeowners hold off selling",
    "living by the seaside is the dream for millions, so forget about winter and enjoy the views In a new series, we highlight the finest coastal homes with the most beautiful views, and on our first trip visit a cottage in picture postcard Devon.",
    "The house and room has a spacious deck from which to take in the sea air while sipping a large glass of rose and watching the sunset, while inside is the living room, kitchen-dining room - complete with Baumatic commercial-style range - and a guest bedroom. Upstairs are three further bedrooms, with the master offering not only a fireplace but magnificent views across the valley and also out to sea, and a bathroom. An attic bedroom has windows front and back, with sea and hillside views. Although no off-road parking, there’s a layby without restrictions. now the waterfront and train lines attract opportunities for imaginative regeneration of old canalside warehouses and industrial buildings, while the Eurostar terminal puts Paris two hours away. The swish flats are future-proofed for home automation and tastefully designed with industrial-style parquet flooring and dark metal finishes. Prices from £895,000. ",
    "The pod has a neat little kitchen with kitchen, a double bed and shower room, while the Grade  cottage boasts a mass of exposed beams, bespoke oak joinery throughout and an inviting wood burner in the sitting room."
];